[package]
name = "freecell-cheat"
version = "0.1.0"
edition = "2024"

[dependencies]
arr_macro = "0.2.1"
derive_more = { version = "2.0.1", features = ["from", "constructor"] }
itertools = "0.13.0"
once_cell = "1.20.2"
